# Generated by Django 4.1.6 on 2023-02-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_department_remove_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
