# Generated by Django 4.1.6 on 2023-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_marks_student_gpa_remove_staff_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(null=True),
        ),
    ]
