# Generated by Django 4.1.6 on 2023-02-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_attendance_alter_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('fee', models.FloatField(null=True)),
            ],
        ),
    ]
