# Generated by Django 4.1.6 on 2023-02-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_collegefee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('package', models.FloatField(null=True)),
            ],
        ),
    ]
