# Generated by Django 4.1.6 on 2023-02-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_placements'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=20)),
                ('ac', models.CharField(max_length=20)),
                ('fee', models.FloatField(null=True)),
            ],
        ),
    ]
